src/charm.py
With the introduction of juju 2.9 labels have changed to follow a more
Kubernetes approach by using standardised app labels and domain specific
Juju labels.
This changes the mutating webhook so that it now supports ignoring
objects that have these new labels avoiding a chicken and egg scenario.
The labels to support are:
- operator.juju.is/name
- app.kubernetes.io/name
Given that label expressions are and together my assumption is the below will work for both 2.9 and pre 2.8 because  the labels won't exists hence the negation will succeed.
=> Allows admission webhook to run on juju 2.9

metadata.yaml, src/charm.py, src/crds.yaml
* Bumps the poddefaults-webhook image to v1.6.0-rc.0
* updates the PodDefault CustomResourceDefinition to use the v1 release of CRDs
=> feat: bump workload to v1.6.0-rc.0 and update CRD to v1

src/charm.py, tests/integration/test_charm.py
See #15 for more detail
This PR changes the scope of the mutatingwebhook created by admission-webhook:
* pods created in a kubeflow user namespace (eg: a namespace labeled by the kubeflow profiles conventions) will be subject to this webhook
* all other pods (those in namespace=kubeflow or completely external to kubeflow) will not be touched by this webhook
This has the beneficial side effect that, if the admission-webhook workload is broken, it **will not** block all pods in the entire kubernetes cluster from creating, as has been reported in the past.  It will however still block all kubeflow user pods in user namespaces
This change was manually tested using the procedure described in #15.  Automated tests will be added later as a separate task
=> Rescope admission-webhook's mutating webhook

config.yaml, src/charm.py, tests/unit/test_operator.py
#69 
Summary of changes:
- Added pebble health check on admission-webhook service port. Check is of type `tcp` to check that the admission webhook service port is open. Admission webhook workload does not own a livenessProbe that we can point the Pebble check to, that would be the usual case in other charms.
- Added update-status event handler to report pebble health check status and set the charm status accordingly.
- Added unit test for update-status event handling.
=> feat update status

src/charm.py
=> fix: revert name change of webhook config

src/templates/webhook_configuration.yaml.j2
fixes #88 in `main`
corresponding to fix merged in 1.7 #89
=> fix: rename `mutatingWebhookConfiguration`

tools/get-images.sh
Repository specific list of images.
Used by CVE scanning workflows and can be used to collect images URL for airgapped setup.
Script is specific for track/1.7 branch to capture all images for that branch.
Branch is handled in kubeflow-ci and bundle automation using bundle file.
Summary of changes:
- Re-designed get images script to retrieve all images for current branch. Branch management is done outside of this script.
=> feat: updated get images script

metadata.yaml
Bump image version to `v1.8.0-rc.0` in preparation for the 1.8 release based on kubeflow/manifests repo tag `v1.8.0-rc.0`.
No changes were observed for the manifests and CRDs.
=> feat: update version to 1.8.0-rc.0

src/charm.py, tests/unit/test_operator.py
cherry-picks ca9e6a7811f5c1bc8410312a5d2837dabb158e8c 
refactors event handling to one event handler where certificates are uploaded to fix issue #126
=> fix: refactor event handling to address certs error (#125)

metadata.yaml
Closes: https://github.com/canonical/admission-webhook-operator/issues/131
I have compared tags `v1.8.0` and `v1.9.0-rc.0` for this files https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook/manifests/overlays/cert-manager
Only change was the image tag.
=> Update admission-webhook to 2.2.0

lib/charms/loki_k8s/v1/loki_push_api.py, metadata.yaml, requirements-integration.txt, requirements-unit.txt, requirements.in, requirements.txt, src/charm.py, tests/integration/test_charm.py, tests/unit/test_operator.py
Use LogForwarder from loki_push_api library to forwards all logs from workload container to Loki. This requires to use ops 2.9 or newer, so it was needed to be updated.
fixes: #133
How I tested it:
```bash
$ tox -e integration -- --keep-models
$ juju switch test-charm-59q5
u1-k8s:admin/testing -> u1-k8s:admin/test-charm-59q5
$ juju consume u1-k8s:cos.loki-logging 
Added u1-k8s:admin/cos.loki-logging as loki-logging
$ juju integrate loki-logging grafana-agent-k8s
$ charmcraft pack 
Created 'admission-webhook_ubuntu-20.04-amd64.charm'.
Charms packed:
admission-webhook_ubuntu-20.04-amd64.charm
$ juju deploy ./admission-webhook_ubuntu-20.04-amd64.charm --resource oci-image=docker.io/kubeflownotebookswg/poddefaults-webhook:v1.9.0-rc.0
Located local charm "admission-webhook", revision 0 …
```
=> Add logging relation to admission-webhook

charmcraft.yaml
Adding the rust toolchain and other dependencies to avoid issues at build time.
Part of canonical/bundle-kubeflow#989
=> build: add rust toolchain and other build packages

metadata.yaml
Closes: https://github.com/canonical/admission-webhook-operator/issues/143
I have compared tags `v1.9.0` and `v1.9.0-rc.0` for this files https://github.com/kubeflow/kubeflow/tree/master/components/admission-webhook/manifests/overlays/cert-manager.
I have also compared from manifest repository
https://github.com/kubeflow/manifests/tree/v1.9.0
Only change was the image tag.
=> chore: update manifests for kf v1.9.0

metadata.yaml
This PR is a backport of #151.
It integrates the PodDefaults rock into admission-webhook for the CKF 1.9 bundle.
=> Backport: Integrate rock

.github/workflows/integrate.yaml, .gitignore, terraform/README.md, terraform/main.tf, terraform/outputs.tf, terraform/variables.tf, terraform/versions.tf, tox.ini
Create a `terraform/` directory that hosts the Terraform module for this charm. It follows the structure proposed in [this spec](https://docs.google.com/document/d/1EG71A2pJ244PQRaGVzGj7Mx2B_bzE4U_OSqx4eeVI1E/edit) and it is follows what was done in canonical/argo-operators#198.
Ref #152
=> feat: Add Terraform module

metadata.yaml
Closes https://warthogs.atlassian.net/browse/KF-6859
Updates the admission-webhook image to `v1.10.0-rc.1`.
There were no changes in manifests, see https://github.com/kubeflow/manifests/tree/v1.10.0-rc.1/apps/admission-webhook/upstream.
=> chore: bump admission-webhook to `v1.10.0-rc.1`

metadata.yaml
Integrate new rock for admission webhook https://hub.docker.com/layers/charmedkubeflow/admission-webhook/1.10.0-rc.0-d5781e6/images/sha256-bf787a02549c87ab1d1ba55b432a818889e7cb670534cbe80b4a0e0c9bac12ec
=> feat: integrate admission-webhook rock for `1.10.0`

.github/workflows/integrate.yaml, .github/workflows/publish.yaml, .github/workflows/release.yaml
Closes #172 
This PR updates the CI to use 24.04:
- We also use `setup-python` to use Python version 3.8.
- We set `destructive-mode` to false since we're now building on a different base than the one we are on.
- We don't need to use `sg` to switch the group when running `tox -e integration`
=> chore(ci): Update CI to use 24.04

metadata.yaml
This PR updates the `upstream-source` image to use the latest version of `admission-webhook`
To view if there were any miscellaneous manifest changes, I compared the 2 tags: https://github.com/kubeflow/manifests/compare/v1.10.0-rc.2...v1.10.0-rc.3
=> chore: Update rock to 1.10 version

charmcraft.yaml
This PR updates `charmcraft.yaml` to use the same format used in the Data Platform team.
=> chore: Update charmcraft.yaml to use the same template as the Data Platform team

.github/concierge.yaml, .github/workflows/integrate.yaml, concierge.yaml, tests/integration/test_charm.py
Closes https://github.com/canonical/bundle-kubeflow/issues/1326
This PR changes the `Setup Operator Enrivonment` job of the `integrate.yaml` action to install Canonical `k8s` using `concierge`. Note that we specify the versions of `juju`, `charmcraft` and `k8s` using environment variables.
There's also a small linting error fixed.
- We also install `tox` since we use it to run the integration tests
- We currently cannot change the Juju model's name that is created by `concierge`, as it is [hardcoded](https://github.com/canonical/concierge/blob/1a0871ecaf6746c79a8cfa2a518458ac42fdc734/internal/juju/juju.go#L226)
=> Update `integrate` action to use Canonical k8s installed via `concierge`

.github/workflows/integrate.yaml, concierge.yaml, tests/integration/test_charm.py
Ref: https://github.com/canonical/bundle-kubeflow/issues/1334
This PR backports the update to use Canonical K8s in our integration tests. Note that we also backport a fix to use `24.04` as base in the `release-charm` action.
=> (backport): Update CI to use Canonical K8s
